version: "3.7"
services:
  web:
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
        VERSION: ${VERSION}
    restart: always
    ports:
      - ${PORT}:8080
